# netlify.toml
[build]
  # Directory where your Angular app is located after building
  base = "/"

  # Command to build your Angular app
  command = "ng build"
 

  # Publish directory for Netlify
  publish = "dist/relu-consultancy-assignment"
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
