[build]
  # Directory where your Angular app is located after building
  base = "frontend"

  # Pre-build command to install dependencies with legacy peer deps
  command = "npm install --legacy-peer-deps && ng build"

  # Publish directory for Netlify
  publish = "dist/quotes_keeper_2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
