[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  
[build]
  # Directory where your Angular app is located after building
  base = "/"
  publish = "/build"

  # Pre-build command to install dependencies with legacy peer deps
  command = "ng build"

  # Publish directory for Netlify
  publish = "/dist/relu-consultancy-assignment/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
