[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  
[build]
  # Directory where your Angular app is located after building
  base = "/"
  #publish = "/build"

  # build command 
  command = "ng build"

  # Publish directory for Netlify
  publish = "dist/relu-consultancy-assignment"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
